version: '3'

services:
  server:
    build: ./server
    env_file: ./server/.env
    ports:
      - "5000:5000"
    volumes:
      - ./server/src:/usr/src
      - /usr/src/__pycache__/

  store:
    build: ./store
    env_file: ./store/.env
    ports:
      - "8080:8080"
    volumes:
      - ./store/src:/usr/src
      - /usr/src/node_modules/
    depends_on:
      - server